name: setup

description: Setup Node, cache and install deps

inputs:
  node_version:
    description: Node Version
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Setup git user
      shell: bash
      run: |
        git config --global user.name '@qwikifiers'
        git config --global user.email 'qwik-ui@users.noreply.github.com'

    - name: Setup pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      with:
        version: 10.15.0

    - name: Use Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node_version }}
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
