name: setup

description: Setup Node, cache and install deps

inputs:
  node_version:
    description: Node Version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user
      shell: bash
      run: |
        git config --global user.name '@qwikifiers'
        git config --global user.email 'qwik-ui@users.noreply.github.com'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
