name: 🐞 Bug Report
description: Something does not work or is flaky! let us know!
labels: ['TYPE: bug', 'STATUS-1: needs triage']
title: '[🐞]'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: package
    attributes:
      label: Which package is affected?
      options:
        - Headless Kit
        - Styled Kit
        - Utils
        - CLI
        - Documentation Website
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      description: 'A clear and concise description of what you expected to happen instead. If you intend to submit a PR for this issue, tell us in the description. Thanks!'
      label: Describe the bug
      placeholder: I am doing ... What I expect is ... What actually happening is ...

    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link via [https://qwikui.com/repro](https://qwikui.com/repro) or clone [this repo](https://github.com/qwikifiers/qwik-ui-stackblitz) and reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required ([Why?](https://antfu.me/posts/why-reproductions-are-required)). If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided after 14 days, it will be auto-closed.
      placeholder: Reproduction URL
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. E.g. if it happens only when running the dev or build script make sure it's clear which one to use.
      placeholder: Run `npm install` followed by `npm run dev`

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{vite,undici,typescript,@builder.io/*,@qwik-ui/*}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
    validations:
      required: false
