export const daisyConfig = {
  variants: {
    accent: 'btn-accent',
    error: 'btn-error',
    ghost: 'btn-ghost',
    info: 'btn-info',
    link: 'btn-link',
    primary: 'btn-primary',
    secondary: 'btn-secondary',
    success: 'btn-success',
    warning: 'btn-warning',
    disabled: 'btn-disabled',
  },
  sizes: {
    xs: 'btn-xs',
    sm: 'btn-sm',
    md: 'btn-md',
    lg: 'btn-lg',
    block: 'btn-block',
    wide: 'btn-wide',
  },
  options: {
    active: 'btn-active',
    outline: 'btn-outline',
    disabled: 'btn-disabled',
    glass: 'glass',
    loading: 'loading',
    noAnimation: 'no-animation',
    circle: 'btn-circle',
    square: 'btn-square',
  },
};
