name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [20, 22]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test
        uses: ./.github/actions/test
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: [test]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1
        with:
          version: pnpm changeset.version
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
